dist: xenial
services:
- postgresql
addons:
  chrome: stable
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
- CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
- curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
- unzip chromedriver_linux64.zip -d ~/bin
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install selenium
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test booth --with-xunit
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: decide-full-guadalfeo-cabina
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  run: "cd decide && python ./manage.py flush && python ./manage.py loaddata db.json"
  on:
    branch: deploy
