# Generated by Django 2.0 on 2020-12-31 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El formato debe ser 8 digitos y una letra mayuscula.', regex='^\\d{8}[A-Z]{1}$')], verbose_name='NIF')),
                ('sexo', models.CharField(choices=[('HOMBRE', 'Man'), ('MUJER', 'Woman'), ('OTRO', 'Other')], default='OTRO', max_length=6, verbose_name='Gender')),
                ('titulo', models.CharField(max_length=100, verbose_name='Grade')),
                ('curso', models.CharField(choices=[('PRIMERO', 'First'), ('SEGUNDO', 'Second'), ('TERCERO', 'Third'), ('CUARTO', 'Fourth'), ('MASTER', 'Master')], default='PRIMERO', max_length=7, verbose_name='Year')),
                ('candidatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.Candidatura', verbose_name='Candidature')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
