# Generated by Django 2.0 on 2021-01-01 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinguser',
            name='edad',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(100)], verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='votinguser',
            name='curso',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Master', 'Master')], default='First', max_length=7, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='votinguser',
            name='sexo',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], default='Other', max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='votinguser',
            name='titulo',
            field=models.CharField(choices=[('Software', 'Software'), ('Computer Technology', 'Computer Technology'), ('Information Technology', 'Information Technology'), ('Health', 'Health')], default='Software', max_length=22, verbose_name='Grade'),
        ),
    ]
